"""Design tokens (Sherlock/voicelm naming, LM Router scale).

Radii follow the house rule: 16px is THE card radius. The smaller steps exist
only for nested/inline chrome (chips, caret rows), never for a card.
"""

from core.theme import PRIMARY

# spacing
SPACE_XXS = 2
SPACE_XS = 4
SPACE_SM = 8
SPACE_MD = 12
SPACE_LG = 16
SPACE_XL = 24
SPACE_XXL = 32
SPACE_XXXL = 48

# typography
FONT_2XS = 10
FONT_XS = 11
FONT_SM = 12
FONT_BODY_SM = 13
FONT_MD = 14
FONT_TITLE = 16
FONT_LG = 20
FONT_XXL = 28

# icons
ICON_XS = 14
ICON_SM = 18
ICON_MD = 22
ICON_LG = 26
ICON_XL = 40
ICON_EMPTY = 48
ICON_BACKDROP = 36
ICON_BACKDROP_RADIUS = 18
ICON_FEATURE = 96
LOGO_SIZE = 32

# spacing steps the scale leaves out (pill gaps live between SM and MD)
SPACE_TIGHT = 6
SPACE_SNUG = 10

# opacity / motion / radii
OPACITY_SUBTLE = 0.05
OPACITY_FAINT = 0.06
OPACITY_LIGHT = 0.08
OPACITY_TINT = 0.10
OPACITY_MEDIUM = 0.12
OPACITY_STRONG = 0.15
OPACITY_EMPHASIS = 0.35
OPACITY_DIM = 0.5
OPACITY_MUTED = 0.5
ANIM_FAST = 120
ANIM_SLOW = 300
RADIUS_SM = 8
RADIUS_CHIP = 10
RADIUS_BUBBLE = 14
RADIUS_MD = 16
RADIUS_LG = 16
RADIUS_XL = 26
RADIUS_PILL = 999
DOT_SIZE = 6
DOT_RADIUS = 3

# component sizes shared by more than one screen
LOG_VIEWPORT = 260
CATALOG_VIEWPORT = 400
CTA_BUTTON_WIDTH = 220
CTA_BUTTON_HEIGHT = 52
DIALOG_WIDTH_MD = 400
DIALOG_WIDTH_LG = 420
DIALOG_WIDTH_XL = 560
DIALOG_HEIGHT_SM = 300
DIALOG_HEIGHT_MD = 420
DIALOG_HEIGHT_LG = 480

__all__ = [
    "ANIM_FAST",
    "ANIM_SLOW",
    "CATALOG_VIEWPORT",
    "CTA_BUTTON_HEIGHT",
    "CTA_BUTTON_WIDTH",
    "DIALOG_HEIGHT_LG",
    "DIALOG_HEIGHT_MD",
    "DIALOG_HEIGHT_SM",
    "DIALOG_WIDTH_LG",
    "DIALOG_WIDTH_MD",
    "DIALOG_WIDTH_XL",
    "DOT_RADIUS",
    "DOT_SIZE",
    "FONT_2XS",
    "FONT_BODY_SM",
    "FONT_LG",
    "FONT_MD",
    "FONT_SM",
    "FONT_TITLE",
    "FONT_XS",
    "FONT_XXL",
    "ICON_BACKDROP",
    "ICON_BACKDROP_RADIUS",
    "ICON_EMPTY",
    "ICON_FEATURE",
    "ICON_LG",
    "ICON_MD",
    "ICON_SM",
    "ICON_XL",
    "ICON_XS",
    "LOGO_SIZE",
    "LOG_VIEWPORT",
    "OPACITY_DIM",
    "OPACITY_EMPHASIS",
    "OPACITY_FAINT",
    "OPACITY_LIGHT",
    "OPACITY_MEDIUM",
    "OPACITY_MUTED",
    "OPACITY_STRONG",
    "OPACITY_SUBTLE",
    "OPACITY_TINT",
    "PRIMARY",
    "RADIUS_BUBBLE",
    "RADIUS_CHIP",
    "RADIUS_LG",
    "RADIUS_MD",
    "RADIUS_PILL",
    "RADIUS_SM",
    "RADIUS_XL",
    "SPACE_LG",
    "SPACE_MD",
    "SPACE_SM",
    "SPACE_SNUG",
    "SPACE_TIGHT",
    "SPACE_XL",
    "SPACE_XS",
    "SPACE_XXL",
    "SPACE_XXS",
    "SPACE_XXXL",
]
